import { Router } from "express";
import Controllers from "../controllers/trails.controller";
const router = Router();

/**
 * @swagger
 * components:
 *  schemas:
 *    Trail:
 *      type: object
 *      properties:
 *              _id:
 *                  type: string
 *                  description: the auto-generated id of trail
 *              trailName:
 *                  type: string
 *                  description: the name of the trail
 *              description:
 *                  type: string
 *                  description: detailed text on trail
 *              country:
 *                  type: object
 *                  properties:
 *                      name:
 *                          type: string
 *                          description: name of the country the trail is located at
 *                      description:
 *                          type: string
 *                          description: description for the country
 *                  required:
 *                  - name
 *              tags:
 *                  type: array
 *                  items:
 *                      type: object
 *                      properties:
 *                          description:
 *                              type: string
 *                              description: description of the tag (e.g. wheelchair access)
 *                          detail:
 *                              type: string
 *                              description: details on the tag (e.g. wheelchair access only until car park)
 *                          specialFlags:
 *                              type: string
 *                              description: special flags attached to the tag (e.g. closed, open)
 *                      required:
 *                      - description
 *                      - detail
 *              review:
 *                  type: array
 *                  items:
 *                      type: object
 *                      properties:
 *                          reviewText:
 *                              type: string
 *                              description: review text
 *                          userid:
 *                              type: string
 *                              description: autogenerated user id
 *                          username:
 *                              type: string
 *                              description: user name
 *                          rating:
 *                              type: integer
 *                              description: a rating assigned with the review (int from 1-5)
 *                          email:
 *                              type: string
 *                              description: email id
 *                          datetime:
 *                              type: date-time
 *                              description: date-time when the review was created
 *                      required:
 *                      - reviewText
 *                      - username
 *                      - rating
 *                      - email
 *                      - datetime
 *              accessibility:
 *                  type: array
 *                  items:
 *                      type: string
 *                      description: accessibility options for the trail (e.g. no vehicle access)
 *              difficulty:
 *                  type: integer
 *                  description: difficulty level of the trail (1-easy, 2-medium, 3-hard, 4-challenging)
 *              timeToComplete:
 *                  type: integer
 *                  description: average time to complete the trail in milliseconds
 *              resourcesInRoute:
 *                  type: array
 *                  items:
 *                      type: object
 *                      properties:
 *                          resourceName:
 *                              type: string
 *                              description: description of resource on trail (e.g. cafe at trail checkpoint)
 *                          type:
 *                              type: type of resource
 *                              description: type of resource (e.g. food)
 *                      required:
 *                      - resourceName
 *              datetime:
 *                  type: date-time
 *                  description: date-time trail object was created in database
 *      required:
 *        - _id
 *        - trailName
 *        - description
 *        - country
 *        - difficulty
 *        - timeToComplete
 *        - datetime
 *      example:
 *          _id: 6164209817a451ca58ebb51e
 *          trailName: Southern Ridges and Labrador Park Loop
 *          description: Southern Ridges and Labrador Park Loop is a 9.0 kilometer lightly trafficked loop trail
 *                       located near Singapore, Central, Singapore that features beautiful wild flowers and is
 *                       rated as moderate. The trail is primarily used for hiking, walking, trail running, and nature trips.
 *          country:
 *              name: Singapore
 *              description: An island country in SEA
 *          tags:
 *              - description: wheelchair access
 *                detail: wheelchair access only until car park
 *                specialFlags: closed
 *          review:
 *              - reviewText: Sunny and warm
 *                userid: T6164209817a451ca58ebb51e
 *                username: johnsmith1
 *                rating: 3
 *                email: johnsmith@gemail.com
 *                datetime: 2015-03-25T12:00:00Z
 *          accessibility: [whellchair, bike, stairs]
 *          difficulty: 3
 *          timeToComplete: 500000
 *          resourcesInRoute:
 *              - resourceName: Public toilet
 *                type: toilet
 *          datetime: 015-03-25T12:00:00Z
 *    Trail Not Found:
 *      type: object
 *      properties:
 *        error:
 *          type: string
 *          description: Error message
 *      example:
 *          error: Requested resource not found!
 */

/**
 * @swagger
 * tags:
 *  name: Trails
 *  description: Trails endpoint
 */

/**
 * @swagger
 * /trails:
 *  get:
 *    summary: returns a list of trails
 *    tags: [Trails]
 *    responses:
 *      200:
 *        description: List of trails
 *        content:
 *          application/json:
 *            schema:
 *              type: array
 *              items:
 *                $ref: '#/components/schemas/Trail'
 *      400:
 *        description: Requested resource not found!
 *      500:
 *        description: Server encountered and internal error!
 */
router.get("/trails", Controllers.getTrails);

export default router;
